### ISSUE TITLE
ENOENT: no such file or directory, open 'D:\dev\stdin'

### ISSUE THREAD

**Issue by Darker** [0x00A/prompt-sync#10]
Filename:
    fs.js:549
      return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                     ^
    
    Error: ENOENT: no such file or directory, open 'D:\dev\stdin'
        at Error (native)
        at Object.fs.openSync (fs.js:549:18)
        at Object.prompt (D:\web\resourcerefresher\node_modules\prompt-sync\index.js:37:15)
        at Object.prompt.question (D:\web\resourcerefresher\refresh.js:15:15)
        at getFiles (D:\web\resourcerefresher\refresh.js:25:23)
        at ReadStream.<anonymous> (D:\web\resourcerefresher\refresh.js:7:31)
        at emitOne (events.js:77:13)
        at ReadStream.emit (events.js:169:7)
        at readableAddChunk (_stream_readable.js:146:16)
        at ReadStream.Readable.push (_stream_readable.js:110:10)

Seems to be lacking any windows support.

**Comment by insin** [comment]
The latest version published to npm (`'3.0.0': '2015-09-01T14:06:16.971Z'`) doesn't contain this change: https://github.com/0x00A/prompt-sync/commit/9d12c79b62cd2aa65a81bd913f3f8ea3a4f93c9a

**Comment by 0x00A** [comment]
just published `+ prompt-sync@3.0.1` to github.

**Comment by insin** [comment]
Thanks, confirming the new version fixes the react-project issue.

**Comment by davidmarkclements** [comment]
fixed
